name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install sphinx

    - name: Generate and Build documentation
      run: |
        sphinx-quickstart -q -p "AppiumExtended" -a "Molokov Klim" docs
        cd docs
        sphinx-apidoc -o ./source/AppiumExtended ../appium_extended
        sphinx-apidoc -o ./source/AppiumGraph ../appium_extended_graph
        sphinx-apidoc -o ./source/AppiumHelpers ../appium_extended_helpers
        sphinx-apidoc -o ./source/AppiumNavigator ../appium_extended_navigator
        sphinx-apidoc -o ./source/AppiumServer ../appium_extended_server
        sphinx-apidoc -o ./source/Terminal ../appium_extended_terminal
        sphinx-apidoc -o ./source/Utils ../appium_extended_utils
        sphinx-apidoc -o ./source/AppiumWebElementExtended ../appium_extended_web_element
        make html  # Или `sphinx-build -b html . _build/html`

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages  # Создание новой ветки, если она не существует
        git rm -rf .  # Удаление всех файлов из предыдущего коммита
        cp -r docs/_build/html/* .  # Копирование сгенерированных HTML-файлов в корневой каталог
        git add .
        git commit -m "Update documentation"
        git push origin gh-pages  # Замените на имя вашей ветки GitHub Pages, если она называется не `gh-pages`
