name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install sphinx

    - name: Build API documentation
      run: |
        cd docs
        sphinx-apidoc -o ./source/AppiumExtended ../appium_extended
        sphinx-apidoc -o ./source/AppiumGraph ../appium_extended_graph
        sphinx-apidoc -o ./source/AppiumHelpers ../appium_extended_helpers
        sphinx-apidoc -o ./source/AppiumNavigator ../appium_extended_navigator
        sphinx-apidoc -o ./source/AppiumServer ../appium_extended_server
        sphinx-apidoc -o ./source/Terminal ../appium_extended_terminal
        sphinx-apidoc -o ./source/Utils ../appium_extended_utils
        sphinx-apidoc -o ./source/AppiumWebElementExtended ../appium_extended_web_element
        make html

    - name: Deploy to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
